# Generated by Django 3.2.10 on 2023-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
