# Generated by Django 3.2.10 on 2023-02-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_customer_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='izdavastvo',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kurs',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
