# Generated by Django 3.2.10 on 2023-02-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20230207_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proizvodnjaPsenicnogBrasnaInfo',
        ),
    ]
